### ISSUE TITLE
terracoin-cli getinfo error

### ISSUE THREAD

**Issue by DiCE1904** [u3mur4/terracoin#3]
When doing terracoin-cli getinfo I get this error, 
terracoin-cli: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory

using Ubuntu 17.10 x64

**Comment by DiCE1904** [comment]
Remade with Ubuntu 16.04.3 x64, works fine. Thanks for your work

**Comment by u3mur4** [comment]
I cannot support every linux distribution (too much work). The only supported os is currently Ubuntu 16.04.3 x64.
