### ISSUE TITLE
fix pipe order

### ISSUE THREAD

**Issue by TheSin-** [u3mur4/terracoin#4]
https://github.com/u3mur4/terracoin/blob/5d4f197e68cd18d07fbb3d87c8577e1038a8718a/trc.py#L232

That line should be

>> sentinel.log 2>&1

as per

https://github.com/terracoin/sentinel/commit/325ea219a0733b32b8c2afab5b85b8f9c22a64c9

**Comment by u3mur4** [comment]
Fixed! Thanks
7a79b84f942b8eb40d24c7eb7143bec897f55be7
