### ISSUE TITLE
Error while loading Shared libraries.

### ISSUE THREAD

**Issue by lucifer911** [u3mur4/terracoin#5]
Hello I am getting this error.

**terracoind: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory**
![error](https://user-images.githubusercontent.com/27394137/34077051-8b6b1d2c-e2c6-11e7-9efc-0bede8f8e1fe.png)

**Comment by u3mur4** [comment]
I only support Ubuntu 16.04 (different package names and managers across linux distros) and probably you are using some other linux distribution. Please use the supported linux distribution or install the missing dependencies. Like boost 1.58 as the error stated.
